openapi: 3.0
info:
    title: API PING
    description: DESCRIBE A SIMPLE "PING" API
paths:
    /ping:
      get:
        summary: Return a simple "pong"
        response:
            '200':
              description: Successful
              content:
                text/plain:
                  type: string
                  example: "pong"
