openapi: 3.0.3
info:
  title: Task Management API
  description: API to manage tasks

paths:
  /tasks:
  get:
    summary: Get all tasks
    response:
      '200':
        description: List of task found
        content:
          application/json:
            schema:
              type: array
              items:
               $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: "Faire les courses"
                  completed: false
                - id: 2
                  title: "Faire le menage"
                  completed: false


components:
 schema:
   task:
     type: object
     required:
       - id
       - title
       - completed
     properties:
       id:
         type: integer
         example: 1
       title:
         type: string
         example: "Faire les course"
       completed:
         type: boolean
         example: false


